version: '3'

services:
  strapi:
    image: docker-strapi:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - asgard
    ports:
      - 1337
    volumes:
      - .:/app

networks:
  asgard: